variables: secrets.yml
templates:
  relax:
    torrent_alive: 0

  tv:
    #proxy: http://localhost:8118
    series:
      - Marvel's Agents of S H I E L D
      - El Ministerio del Tiempo
    configure_series:
      from:
        trakt_list:
          username: '{? trakt.usr ?}'
          account: '{? trakt.usr ?}'
          strip_dates: yes
          list: Download
          type: shows
      settings:
        qualities:
          - 720p+
          - webrip+
          - "!10bit"
        timeframe: 12 hours
        upgrade: yes
    #content_size:
    #  min: 200
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.r00'
      reject: 
        - 'password.txt'
        - '*.wmv'
    exists_series:
      path:
        - '{? paths.shows ?}'
        - '{? paths.incomplete ?}'
      allow_different_qualities: better
    thetvdb_lookup: yes
    set:
      series_name:
        replace: ['From \[ WWW.TORRENTING.COM \] - ', '']
      path: '{? paths.incomplete ?}'
      movedone: "{? paths.shows ?}/{{ series_name }}/Season {{ series_season }}"
      content_filename: >
        {{ series_name }} - {{ series_id }}
        {% if ep_name|default(False) %}- {{ ep_name }} {% endif %}- {{ quality|upper }}
        {% if proper_count %}- proper{% if proper_count > 1 %}{{ proper_count }}{% endif %}{% endif %}
    subliminal:
      languages:
        - eng
      exact_match: yes
      providers: [addic7ed, opensubtitles, tvsubtitles]
    deluge:
      password: '{? deluge.pwd ?}'
      label: tv_show
      main_file_only: yes
    list_add:
      - trakt_list:
          username: '{? trakt.usr ?}'
          account: '{? trakt.usr ?}'
          list: collection
          type: episodes
    notify:
      entries:
        title: '{{series_name}}'
        message: '{{series_id}}'
        via:
          - pushbullet:
              api_key: '{? pushbullet.key ?}'
              device: '{? pushbullet.phone ?}'
    

  movies:
    quality:
      - 720p+
      - hdtv+
    exists_movie:
      - '{? paths.movies ?}'
      - '{? paths.incomplete ?}'
    seen_movies: loose
    proper_movies: yes
    #torrent_alive: 10
    regexp:
      reject:
        - YIFY
    set:
      path: '{? paths.incomplete ?}'
      movedone: '{? paths.movies ?}'
    deluge:
      password: '{? deluge.pwd ?}'
      label: movie
      main_file_only: yes
    list_add:
      - trakt_list:
          username: '{? trakt.usr ?}'
          account: '{? trakt.usr ?}'
          list: collection
          type: movies
    verify_ssl_certificates: no
    

tasks:
  piratebay_hires_tv:
    template: tv
    #rss: https://thepiratebay.org/rss/new/208
    #rss: http://uj3wazyk5u4hnvtk.onion/rss/new/208
    html:
      url: https://thepiratebay.org/browse/208/{{i}}/3/0
      links_re: [ magnet ]
      title_from: url
      increment:
        from: 0
        to: 3
    priority: 20

  piratebay_lores_tv:
    template: tv
    #rss: https://thepiratebay.org/rss/new/205
    html:
      url: https://thepiratebay.org/browse/205/{{i}}/3/0
      links_re: [ magnet ]
      title_from: url
      increment:
        from: 0
        to: 3
    priority: 20

  extratorrent_tv:
    template: tv
    rss: https://extratorrent.cc/rss.xml?cid=8&type=last
    priority: 30
    verify_ssl_certificates: no

  #extratorrent_hires_tv:
  #  template: tv
  #  rss: https://extratorrent.cc/rss.xml?type=search&search=720p&cid=8
  #  priority: 30
  #  verify_ssl_certificates: no

  kickass_tv:
    template: tv
    rss:
      url: http://katcr.to/tv/?rss=1
      other_fields: ['torrent:magnetURI']
      link: 'torrent:magnetURI'
    magnets: yes
    priority: 30
    verify_ssl_certificates: no

  eztv:
    template: tv
    #rss: http://rss.thepiratebay.se/user/d17c6a45441ce0bc0c057f19057f95e1
    rss: http://extratorrent.cc/rss.xml?type=search&search=eztv&cid=8
    #rss:
    #  url: https://kat.cr/usearch/eztv%20720p%20category%3Atv/?rss=1
    #  other_fields: ['torrent:magnetURI']
    #  link: 'torrent:magnetURI'
    #magnets: yes
    #verify_ssl_certificates: no
    priority: 10

  publichd:
    template: tv
    #rss: http://maxters.net/apps/pbay/search/publichd/0/3/208
    rss: http://extratorrent.cc/rss.xml?type=search&search=publichd&cid=8
    #rss:
    #  url: https://kat.cr/usearch/publichd%20720p%20category%3Atv/?rss=1
    #  other_fields: ['torrent:magnetURI']
    #  link: 'torrent:magnetURI'
    #magnets: yes
    #verify_ssl_certificates: no
    priority: 20

  #showrss:
  #  template: tv
  #  rss: http://showrss.karmorra.info/rss.php?user_id=52263&hd=1&proper=1

  #torrentz_hires_shows:
  #  template: tv
  #  rss: http://torrentz.eu/feedA?q=tv+shows+highres+-porn
  #  priority: 11

  #torrentz_lores_shows:
  #  template: tv
  #  rss: http://torrentz.eu/feedA?q=tv+shows+-porn
  #  priority: 21

  #el_ministerio:
  #  template: tv
  #  rss:
  #    url: http://kat.cr/usearch/El%20ministerio%20del%20tiempo/?rss=1
  #    other_fields: ['torrent:magnetURI']
  #    link: 'torrent:magnetURI'
  #    ascii: yes
  #  magnets: yes
  #  priority: 25

  #isohunt_hires_shows:
  #  template: tv
  #  rss: http://isohunt.com/js/rss/720p?iht=3&noSL
  #  priority: 3


  trakt_movies:
    priority: 50
    trakt_list:
      username: '{? trakt.usr ?}'
      account: '{? trakt.usr ?}'
      list: watchlist
      type: movies
    accept_all: yes
    list_add:
      - movie_list: movies
    disable:
      - seen # seen needs to be disabled since all the titles that movie queue will emit were seen when they were added to the queue

  discover_movies:
    priority: 51
    template: movies
    discover:
      what:
        - movie_list: movies
      from:
        - piratebay: yes
        #- torrentz: verified
        - extratorrent:
            category: movies
        #- kat:
        #    category: movies
        #    verified: yes
    list_match:
      from:
        - movie_list: movies
    notify:
      entries:
        title: '{{movie_name}} ({{movie_year}})'
        via:
          - pushbullet:
              api_key: '{? pushbullet.key ?}'
              device: '{? pushbullet.phone ?}'


  scan_dir:
    template: tv
    filesystem: '{? paths.home ?}'
    accept_all: yes
    manual: yes  # need to use flexget --task=scan_dir
      #- tv
      #- relax

  from_file:
    template: tv
    text:
      url: '{? paths.home ?}/list'
      entry:
        title: 'TITLE: (.*) URL:'
        url: 'URL: (.*)'
    accept_all: yes
    manual: yes

