secrets: secrets.yml
templates:
  relax:
    torrent_alive: 0

  tv:
    series:
      - Marvel's Agents of S H I E L D
      - El Ministerio del Tiempo
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.usr }}'
          password: '{{ secrets.trakt.pwd }}'
          strip_dates: yes
          list: Download
          type: shows
      settings:
        qualities:
          - "!h265"
          - "<=720p"
          - hdtv-bluray
          - "!480p"
        timeframe: 12 hours
        upgrade: yes
    #content_size:
    #  min: 200
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.r00'
      reject: 
        - 'password.txt'
        - '*.wmv'
    regexp:
      reject:
        - hevc
    exists_series:
      path:
        - '{{ secrets.paths.shows }}'
        - '{{ secrets.paths.incomplete }}'
      allow_different_qualities: better
    thetvdb_lookup: yes
    set:
      path: '{{ secrets.paths.incomplete }}'
      movedone: "{{ secrets.paths.shows }}/{{ series_name }}/Season {{ series_season }}"
      content_filename: >
        {{ series_name }} - {{ series_id }}
        {% if ep_name|default(False) %}- {{ ep_name }} {% endif %}- {{ quality|upper }}
        {% if proper_count %}- proper{% if proper_count > 1 %}{{ proper_count }}{% endif %}{% endif %}
    deluge:
      password: '{{ secrets.deluge.pwd }}'
      label: tv_show
      main_file_only: yes
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      list: collection
    pushbullet:
      apikey: '{{ secrets.pushbullet.key }}'
      device: '{{ secrets.pushbullet.phone }}'
      title: '{{series_name}}'
      body: '{{series_id}}'
    

  movies:
    quality:
      - 720p+
      - hdtv+
    exists_movie:
      - '{{ secrets.paths.movies }}'
      - '{{ secrets.paths.incomplete }}'
    seen_movies: loose
    proper_movies: yes
    #torrent_alive: 10
    set:
      path: '{{ secrets.paths.incomplete }}'
      movedone: '{{ secrets.paths.movies }}'
    deluge:
      password: '{{ secrets.deluge.pwd }}'
      label: movie
      main_file_only: yes
    trakt_add:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      list: collection
    verify_ssl_certificates: no
    

tasks:
  #piratebay_hires_tv:
  #  template: tv
  #  rss: http://rss.thepiratebay.se/208
  #  priority: 20

  #piratebay_lores_tv:
  #  template: tv
  #  rss: http://rss.thepiratebay.se/205
  #  priority: 20

  kickass_hires_tv:
    template: tv
    rss:
      url: https://kat.cr/usearch/720p%20category%3Atv/?rss=1
      other_fields: ['torrent:magnetURI']
      link: 'torrent:magnetURI'
    magnets: yes
    priority: 30
    verify_ssl_certificates: no

  eztv:
    template: tv
    #rss: http://rss.thepiratebay.se/user/d17c6a45441ce0bc0c057f19057f95e1
    rss:
      url: https://kat.cr/usearch/eztv%20720p%20category%3Atv/?rss=1
      other_fields: ['torrent:magnetURI']
      link: 'torrent:magnetURI'
    magnets: yes
    verify_ssl_certificates: no
    priority: 10

  publichd:
    template: tv
    #rss: http://maxters.net/apps/pbay/search/publichd/0/3/208
    rss:
      url: https://kat.cr/usearch/publichd%20720p%20category%3Atv/?rss=1
      other_fields: ['torrent:magnetURI']
      link: 'torrent:magnetURI'
    magnets: yes
    verify_ssl_certificates: no
    priority: 20

  #showrss:
  #  template: tv
  #  rss: http://showrss.karmorra.info/rss.php?user_id=52263&hd=1&proper=1

  torrentz_hires_shows:
    template: tv
    rss: http://torrentz.eu/feedA?q=tv+shows+highres+-porn
    priority: 11

  torrentz_lores_shows:
    template: tv
    rss: http://torrentz.eu/feedA?q=tv+shows+-porn
    priority: 21

  el_ministerio:
    template: tv
    rss:
      url: http://kat.cr/usearch/El%20ministerio%20del%20tiempo/?rss=1
      other_fields: ['torrent:magnetURI']
      link: 'torrent:magnetURI'
      ascii: yes
    magnets: yes
    priority: 25

  #isohunt_hires_shows:
  #  template: tv
  #  rss: http://isohunt.com/js/rss/720p?iht=3&noSL
  #  priority: 3


  trakt_movies:
    priority: 50
    trakt_list:
      username: '{{ secrets.trakt.usr }}'
      password: '{{ secrets.trakt.pwd }}'
      list: watchlist
      type: movies
    accept_all: yes
    movie_queue: add

  discover_movies:
    priority: 51
    template: movies
    discover:
      what:
        - emit_movie_queue: yes
      from:
        #- piratebay: yes
        - torrentz: verified
        - kat:
            category: movies
            verified: yes
    movie_queue: add
    pushbullet:
      apikey: '{{ secrets.pushbullet.key }}'
      device: '{{ secrets.pushbullet.phone }}'
      body: '{{movie_name}} ({{movie_year}})'


  scan_dir:
    template: tv
    filesystem: '{{ secrets.paths.home }}'
    accept_all: yes
    manual: yes  # need to use flexget --task=scan_dir
      #- tv
      #- relax

  from_file:
    template: tv
    text:
      url: '{{ secrets.paths.home }}/list'
      entry:
        title: 'TITLE: (.*) URL:'
        url: 'URL: (.*)'
    accept_all: yes
    manual: yes

